/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uRya4bPcEVLtpSKZT89NQm

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsesZja8J5Cu9Z } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ESZja8j5CU9z/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsesZja8J5Cu9Z
});
