/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uRya4bPcEVLtpSKZT89NQm

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uRya4bPcEVLtpSKZT89NQm/projectModule

const data = {
  base: `${"plasmic_tokens_uRya4bPcEVLtpSKZT89NQm"} ${"plasmic_tokens_5ZtnypMovRHeeP3YTdPCYL"} ${"plasmic_tokens_4vjRXvnb4XuY6J15w9oRcQ"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
