/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uRya4bPcEVLtpSKZT89NQm
// Component: c-RxGCx-FD0m

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Logo from "../../Logo"; // plasmic-import: MTEjSDqstzWW/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uRya4bPcEVLtpSKZT89NQm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uRya4bPcEVLtpSKZT89NQm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicFooterSection.module.css"; // plasmic-import: c-RxGCx-FD0m/css

import TwitterIcon from "./icons/PlasmicIcon__Twitter"; // plasmic-import: oL4x01t7uaop/icon
import GithubIcon from "./icons/PlasmicIcon__Github"; // plasmic-import: vItErr5tgD4F/icon
import LinkedinIcon from "./icons/PlasmicIcon__Linkedin"; // plasmic-import: nxElTkSp6Ps_/icon

createPlasmicElementProxy;

export type PlasmicFooterSection__VariantMembers = {};
export type PlasmicFooterSection__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooterSection__VariantsArgs;
export const PlasmicFooterSection__VariantProps = new Array<VariantPropType>();

export type PlasmicFooterSection__ArgsType = {};
type ArgPropType = keyof PlasmicFooterSection__ArgsType;
export const PlasmicFooterSection__ArgProps = new Array<ArgPropType>();

export type PlasmicFooterSection__OverridesType = {
  root?: Flex__<"div">;
  logo?: Flex__<typeof Logo>;
};

export interface DefaultFooterSectionProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooterSection__RenderFunc(props: {
  variants: PlasmicFooterSection__VariantsArgs;
  args: PlasmicFooterSection__ArgsType;
  overrides: PlasmicFooterSection__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_uRya4bPcEVLtpSKZT89NQm",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames("all", sty.freeBox___2MJbO)}>
        <div className={classNames("all", sty.freeBox__qh0Xc)}>
          <Logo
            data-plasmic-name={"logo"}
            data-plasmic-override={overrides.logo}
            _50Opaque={true}
          />

          <div className={classNames("all", sty.freeBox__xAg98)}>
            <div className={classNames("all", "__wab_text", sty.text__ygd8V)}>
              {"Connect with us"}
            </div>
            <div className={classNames("all", sty.freeBox__f5HHt)}>
              <TwitterIcon
                className={classNames("all", sty.svg__sUsSc)}
                role={"img"}
              />

              <GithubIcon
                className={classNames("all", sty.svg__aHhrb)}
                role={"img"}
              />

              <LinkedinIcon
                className={classNames("all", sty.svg___206XM)}
                role={"img"}
              />
            </div>
          </div>
        </div>
        <div className={classNames("all", sty.freeBox__eSOwO)}>
          <div className={classNames("all", "__wab_text", sty.text__qvVwx)}>
            {"Product"}
          </div>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link__lfCuC
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Pricing"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link__fZxAi
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Log in"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link___6Iz62
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Integrations"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link__r0Dmy
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Insights"}
          </PlasmicLink__>
        </div>
        <div className={classNames("all", sty.freeBox__qQn)}>
          <div className={classNames("all", "__wab_text", sty.text__uRtRf)}>
            {"Support"}
          </div>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link__urxAw
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Documentation"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link__lRvXe
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"FAQs"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link__npxLj
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Status"}
          </PlasmicLink__>
        </div>
        <div className={classNames("all", sty.freeBox__nGWr)}>
          <div className={classNames("all", "__wab_text", sty.text__ojXEh)}>
            {"Company"}
          </div>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link___2R3Wr
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Contact us"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link__fnqZn
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Careers"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link__fmzU5
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"About"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              "all",
              "a",
              "a__uRya4",
              "__wab_text",
              sty.link___0Zqj1
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Media"}
          </PlasmicLink__>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "logo"],
  logo: ["logo"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  logo: typeof Logo;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooterSection__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooterSection__VariantsArgs;
    args?: PlasmicFooterSection__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFooterSection__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFooterSection__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooterSection__ArgProps,
          internalVariantPropNames: PlasmicFooterSection__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooterSection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterSection";
  } else {
    func.displayName = `PlasmicFooterSection.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterSection = Object.assign(
  // Top-level PlasmicFooterSection renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    logo: makeNodeComponent("logo"),

    // Metadata about props expected for PlasmicFooterSection
    internalVariantProps: PlasmicFooterSection__VariantProps,
    internalArgProps: PlasmicFooterSection__ArgProps
  }
);

export default PlasmicFooterSection;
/* prettier-ignore-end */
