/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uRya4bPcEVLtpSKZT89NQm
// Component: Uo3eafDeLnt0

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: 50wLRkUx8jTs/component
import Divider from "../../Divider"; // plasmic-import: 1vR5bsG7sR4C/component
import TextField from "../../TextField"; // plasmic-import: qbdePUKEIrAD/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uRya4bPcEVLtpSKZT89NQm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uRya4bPcEVLtpSKZT89NQm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicSignUpPrompt.module.css"; // plasmic-import: Uo3eafDeLnt0/css

import AppleIcon from "./icons/PlasmicIcon__Apple"; // plasmic-import: REXo9mPJZrhR/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: 3A1EOlbHtG0o/icon
import GoogleIcon from "./icons/PlasmicIcon__Google"; // plasmic-import: s9BPYlGYPpZY/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: fjt-EIaQJSl_/icon

createPlasmicElementProxy;

export type PlasmicSignUpPrompt__VariantMembers = {};
export type PlasmicSignUpPrompt__VariantsArgs = {};
type VariantPropType = keyof PlasmicSignUpPrompt__VariantsArgs;
export const PlasmicSignUpPrompt__VariantProps = new Array<VariantPropType>();

export type PlasmicSignUpPrompt__ArgsType = {};
type ArgPropType = keyof PlasmicSignUpPrompt__ArgsType;
export const PlasmicSignUpPrompt__ArgProps = new Array<ArgPropType>();

export type PlasmicSignUpPrompt__OverridesType = {
  root?: Flex__<"div">;
  name?: Flex__<typeof TextField>;
  email?: Flex__<typeof TextField>;
  password?: Flex__<typeof TextField>;
};

export interface DefaultSignUpPromptProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSignUpPrompt__RenderFunc(props: {
  variants: PlasmicSignUpPrompt__VariantsArgs;
  args: PlasmicSignUpPrompt__ArgsType;
  overrides: PlasmicSignUpPrompt__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "name.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "email.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "password.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const currentUser = useCurrentUser?.() || {};

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_uRya4bPcEVLtpSKZT89NQm",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames("all", sty.freeBox__tnWbr)}>
        <div className={classNames("all", sty.freeBox__qQ0Bw)}>
          <div className={classNames("all", "__wab_text", sty.text__tUa4S)}>
            {"Sign up with"}
          </div>
          <div className={classNames("all", sty.freeBox___93JZ)}>
            <Button
              className={classNames("__wab_instance", sty.button__hTzFq)}
              color={"neutral"}
              iconStart={true}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__rMm3F)}
                >
                  {"Apple"}
                </div>
              }
              start={
                <AppleIcon
                  className={classNames("all", sty.svg___24C4Y)}
                  role={"img"}
                />
              }
              submitsForm={true}
              type={"bordered"}
            />

            <Button
              className={classNames("__wab_instance", sty.button__yUnpw)}
              color={"neutral"}
              iconStart={true}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__g2Mc5)}
                >
                  {"Google"}
                </div>
              }
              start={
                <GoogleIcon
                  className={classNames("all", sty.svg___99S3G)}
                  role={"img"}
                />
              }
              submitsForm={true}
              type={"bordered"}
            />
          </div>
          <div className={classNames("all", sty.freeBox__bGcxE)}>
            <Divider
              className={classNames("__wab_instance", sty.divider___9Kh77)}
            />

            <div className={classNames("all", "__wab_text", sty.text___0Ej4)}>
              {"Or"}
            </div>
            <Divider
              className={classNames("__wab_instance", sty.divider___4Vo2R)}
            />
          </div>
          <div className={classNames("all", sty.freeBox__zs2O)}>
            <TextField
              data-plasmic-name={"name"}
              data-plasmic-override={overrides.name}
              className={classNames("__wab_instance", sty.name)}
              inputMode={"text"}
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["name", "value"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Full Name"}
              showLabel={false}
              type={"text"}
            />

            <TextField
              data-plasmic-name={"email"}
              data-plasmic-override={overrides.email}
              className={classNames("__wab_instance", sty.email)}
              inputMode={"email"}
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["email", "value"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Email"}
              showLabel={false}
              type={"email"}
            />

            <TextField
              data-plasmic-name={"password"}
              data-plasmic-override={overrides.password}
              className={classNames("__wab_instance", sty.password)}
              onChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["password", "value"]).apply(
                  null,
                  eventArgs
                );

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Password"}
              showLabel={false}
              type={"password"}
            />

            <Button
              className={classNames("__wab_instance", sty.button__sTkQ)}
              label={
                <div
                  className={classNames("all", "__wab_text", sty.text__nN9T)}
                >
                  {"Start your account"}
                </div>
              }
              size={"extraLarge"}
              submitsForm={true}
            />
          </div>
        </div>
        <Divider className={classNames("__wab_instance", sty.divider__yTz0N)} />

        <div className={classNames("all", sty.freeBox__tbtlw)}>
          <div className={classNames("all", "__wab_text", sty.text__l8VMu)}>
            {
              "A cras sagittis odio vestibulum pulvinar a eget hendrerit id vestibulum a leo sociosqu dictumst dictumst natoque magnis parturient."
            }
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "name", "email", "password"],
  name: ["name"],
  email: ["email"],
  password: ["password"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  name: typeof TextField;
  email: typeof TextField;
  password: typeof TextField;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSignUpPrompt__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSignUpPrompt__VariantsArgs;
    args?: PlasmicSignUpPrompt__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSignUpPrompt__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSignUpPrompt__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSignUpPrompt__ArgProps,
          internalVariantPropNames: PlasmicSignUpPrompt__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSignUpPrompt__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignUpPrompt";
  } else {
    func.displayName = `PlasmicSignUpPrompt.${nodeName}`;
  }
  return func;
}

export const PlasmicSignUpPrompt = Object.assign(
  // Top-level PlasmicSignUpPrompt renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    _name: makeNodeComponent("name"),
    email: makeNodeComponent("email"),
    password: makeNodeComponent("password"),

    // Metadata about props expected for PlasmicSignUpPrompt
    internalVariantProps: PlasmicSignUpPrompt__VariantProps,
    internalArgProps: PlasmicSignUpPrompt__ArgProps
  }
);

export default PlasmicSignUpPrompt;
/* prettier-ignore-end */
