/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uRya4bPcEVLtpSKZT89NQm
// Component: _AeAK2Aiqyls

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: 0cn6bKm8EegY/component
import { Video } from "@plasmicpkgs/plasmic-basic-components";
import Button from "../../Button"; // plasmic-import: 50wLRkUx8jTs/component
import SignUpPrompt from "../../SignUpPrompt"; // plasmic-import: Uo3eafDeLnt0/component
import Section from "../../Section"; // plasmic-import: pc3pfBOeZjrK/component
import ValueProp from "../../ValueProp"; // plasmic-import: QReoVcGTgpc7/component
import ListItem from "../../ListItem"; // plasmic-import: UiOBWuY6Cm0K/component
import PriceCard from "../../PriceCard"; // plasmic-import: GaCJBt6z3wFB/component
import Banner from "../../Banner"; // plasmic-import: Y7XsijUWoqCm/component
import Testimonial from "../../Testimonial"; // plasmic-import: Vss7SSBnCn9G/component
import CallToActionSection from "../../CallToActionSection"; // plasmic-import: yqix2HbcOLlp/component
import FooterSection from "../../FooterSection"; // plasmic-import: c-RxGCx-FD0m/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uRya4bPcEVLtpSKZT89NQm/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uRya4bPcEVLtpSKZT89NQm/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicHomepage.module.css"; // plasmic-import: _AeAK2Aiqyls/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: fjt-EIaQJSl_/icon
import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: pZlwBTLqkRBX/icon
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: bmeJVMkmp4mP/icon
import CheckCircleIcon from "./icons/PlasmicIcon__CheckCircle"; // plasmic-import: DxcfXIKsieRY/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Home",

    openGraph: {
      title: "Home"
    },
    twitter: {
      card: "summary" as const,
      title: "Home"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  headerHeroSection?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  htmlVideo?: Flex__<typeof Video>;
  button?: Flex__<typeof Button>;
  signUpPrompt?: Flex__<typeof SignUpPrompt>;
  valuePropsSection?: Flex__<typeof Section>;
  checkpointsSection?: Flex__<typeof Section>;
  pricingSection?: Flex__<typeof Section>;
  shopBannersSection?: Flex__<typeof Section>;
  logoCloudSection?: Flex__<typeof Section>;
  testimonialsSection?: Flex__<typeof Section>;
  callToActionSection?: Flex__<typeof CallToActionSection>;
  footerSection?: Flex__<typeof FooterSection>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const canvasRef = React.useRef<HTMLCanvasElement | null>(null);

  React.useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) {
      return;
    }

    const gl = canvas.getContext("webgl2");
    if (!gl) {
      return;
    }

    const vertexShaderSource = `#version 300 es
precision highp float;
in vec4 position;
void main() {
  gl_Position = vec4(position);
}`;

    const fragmentShaderSource = `#version 300 es
#if __VERSION__ < 130
#define TEXTURE2D texture2D
#else
#define TEXTURE2D texture
#endif
precision highp float;
out vec4 fragColor;
uniform vec2 u_resolution;
uniform float u_time;
uniform sampler2D u_video;
  
#define R u_resolution
#define T u_time

float character(int n, vec2 p) {
  p = floor(p*vec2(-4., 4.) + 2.5);
  if (clamp(p.x, 0., 4.) == p.x) {
    if (clamp(p.y, 0., 4.) == p.y) {
      int a = int(round(p.x) + 5. * round(p.y));
      if (((n >> a) & 1) == 1) return 1.;
    }
  }
  return 0.;
}

void main(){ 
  vec2 F = gl_FragCoord.xy;
  vec2 uv = (2.*F.xy-R.xy)/max(R.x,R.y);
    
  float size = 5.;
  float srez = size*2.;
  vec3 col = texture(u_video, floor(F.xy/srez)*srez/R.xy).rgb;  
  float gray = .3 * col.r + .6 * col.g + .1 * col.b;

  int n =  0000;

  if (gray > 0.0233) n = 4096;
  if (gray > 0.0465) n = 131200;
  if (gray > 0.0698) n = 4329476;
  if (gray > 0.0930) n = 459200;
  if (gray > 0.1163) n = 4591748;
  if (gray > 0.1395) n = 12652620;
  if (gray > 0.1628) n = 14749828;
  if (gray > 0.1860) n = 18393220;
  if (gray > 0.2093) n = 15239300;
  if (gray > 0.2326) n = 17318431;
  if (gray > 0.2558) n = 32641156;
  if (gray > 0.2791) n = 18393412;
  if (gray > 0.3023) n = 18157905;
  if (gray > 0.3256) n = 17463428;
  if (gray > 0.3488) n = 14954572;
  if (gray > 0.3721) n = 13177118;
  if (gray > 0.3953) n = 18405034;
  if (gray > 0.4186) n = 16269839;
  if (gray > 0.4419) n = 15018318;
  if (gray > 0.4651) n = 18400814;
  if (gray > 0.4884) n = 33081316;
  if (gray > 0.5116) n = 15255086;
  if (gray > 0.5349) n = 32045584;
  if (gray > 0.5581) n = 6566222;
  if (gray > 0.5814) n = 15022158;
  if (gray > 0.6047) n = 18444881;
  if (gray > 0.6279) n = 16272942;
  if (gray > 0.6512) n = 18415153;
  if (gray > 0.6744) n = 32641183;
  if (gray > 0.6977) n = 32540207;
  if (gray > 0.7209) n = 18732593;
  if (gray > 0.7442) n = 18667121;
  if (gray > 0.7674) n = 16267326;
  if (gray > 0.7907) n = 32575775;
  if (gray > 0.8140) n = 15022414;
  if (gray > 0.8372) n = 15255537;
  if (gray > 0.8605) n = 32032318;
  if (gray > 0.8837) n = 32045617;
  if (gray > 0.9070) n = 33061392;
  if (gray > 0.9302) n = 33061407;
  if (gray > 0.9535) n = 32045630;
  if (gray > 0.9767) n = 11512810;

  vec2 p = mod(F.xy/size, 2.) - vec2(1);
  col = col*character(n, p);
  fragColor = vec4(col, 1);
}
`;

    const compileShader = (type: number, source: string) => {
      const shader = gl.createShader(type);
      if (!shader) {
        throw new Error("Unable to create shader");
      }
      gl.shaderSource(shader, source);
      gl.compileShader(shader);
      if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
        const error = gl.getShaderInfoLog(shader);
        gl.deleteShader(shader);
        throw new Error(`Shader compile failed: ${error}`);
      }
      return shader;
    };

    const vertexShader = compileShader(gl.VERTEX_SHADER, vertexShaderSource);
    const fragmentShader = compileShader(gl.FRAGMENT_SHADER, fragmentShaderSource);
    const program = gl.createProgram();
    if (!program) {
      return;
    }
    gl.attachShader(program, vertexShader);
    gl.attachShader(program, fragmentShader);
    gl.linkProgram(program);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      const error = gl.getProgramInfoLog(program);
      gl.deleteProgram(program);
      throw new Error(`Program link failed: ${error}`);
    }

    const positionBuffer = gl.createBuffer();
    const vao = gl.createVertexArray();
    if (!positionBuffer || !vao) {
      return;
    }

    gl.bindVertexArray(vao);
    gl.bindBuffer(gl.ARRAY_BUFFER, positionBuffer);
    gl.bufferData(
      gl.ARRAY_BUFFER,
      new Float32Array([-1, -1, 0, 1, -1, 0, -1, 1, 0, -1, 1, 0, 1, -1, 0, 1, 1, 0]),
      gl.STATIC_DRAW
    );

    const positionLoc = gl.getAttribLocation(program, "position");
    gl.enableVertexAttribArray(positionLoc);
    gl.vertexAttribPointer(positionLoc, 3, gl.FLOAT, false, 0, 0);

    const texture = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, texture);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);

    const video = document.createElement("video");
    video.src = "https://res.cloudinary.com/dvqxhfwiw/video/upload/Camera_j9jkvr.mp4";
    video.crossOrigin = "anonymous";
    video.loop = true;
    video.muted = true;
    video.playsInline = true;
    video.play().catch(() => {});

    const uTimeLoc = gl.getUniformLocation(program, "u_time");
    const uResolutionLoc = gl.getUniformLocation(program, "u_resolution");
    const uVideoLoc = gl.getUniformLocation(program, "u_video");

    let rafId = 0;
    const resizeCanvas = () => {
      const dpr = window.devicePixelRatio || 1;
      const bufferScale = Math.max(1, dpr * 2); // increase render buffer beyond display DPI
      const width = Math.floor(canvas.clientWidth * bufferScale);
      const height = Math.floor(canvas.clientHeight * bufferScale);
      if (canvas.width !== width || canvas.height !== height) {
        canvas.width = width;
        canvas.height = height;
      }
    };

    const render = (time: number) => {
      resizeCanvas();
      gl.viewport(0, 0, canvas.width, canvas.height);
      if (video.readyState >= video.HAVE_CURRENT_DATA) {
        gl.bindTexture(gl.TEXTURE_2D, texture);
        gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, video);
      }

      gl.useProgram(program);
      gl.bindVertexArray(vao);
      gl.uniform1f(uTimeLoc, time * 0.001);
      gl.uniform2f(uResolutionLoc, canvas.width, canvas.height);
      gl.uniform1i(uVideoLoc, 0);
      gl.activeTexture(gl.TEXTURE0);
      gl.bindTexture(gl.TEXTURE_2D, texture);
      gl.drawArrays(gl.TRIANGLES, 0, 6);
      rafId = requestAnimationFrame(render);
    };

    const handleResize = () => resizeCanvas();
    window.addEventListener("resize", handleResize);
    rafId = requestAnimationFrame(render);

    return () => {
      cancelAnimationFrame(rafId);
      window.removeEventListener("resize", handleResize);
      video.pause();
    };
  }, []);

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_uRya4bPcEVLtpSKZT89NQm",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"headerHeroSection"}
            data-plasmic-override={overrides.headerHeroSection}
            className={classNames("all", sty.headerHeroSection)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <canvas
              data-plasmic-name={"htmlVideo"}
              data-plasmic-override={overrides.htmlVideo}
              className={classNames("__wab_instance", sty.htmlVideo)}
              ref={canvasRef}
            />

            <div className={classNames("all", sty.columns__q7I9)}>
              <div className={classNames("all", sty.column__bvJJi)}>
                <div className={classNames("all", sty.freeBox__zg7TP)}>
                  <div className={classNames("all", sty.freeBox__ft27N)}>
                    <div className={classNames("all", sty.freeBox__m8Lgl)}>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__ahqo
                        )}
                      >
                        {"Updated!"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__voPgm
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"Designs that "}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span plasmic_default__span__uRya4"
                          }
                          style={{ textDecoration: "underline" }}
                        >
                          {"adapt"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text___6SbN
                      )}
                    >
                      {
                        "Orci dui condimentum rutrum laoreet hac purus porta sem sem a vivamus a posuere vel molestie."
                      }
                    </div>
                  </div>
                  <div className={classNames("all", sty.freeBox___4LFq6)}>
                    <Button
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      className={classNames("__wab_instance", sty.button)}
                      color={"neutral"}
                      end={
                        <ChevronRightIcon
                          className={classNames("all", sty.svg__hf1DH)}
                          role={"img"}
                        />
                      }
                      iconEnd={true}
                      label={
                        <div
                          className={classNames(
                            "all",
                            "__wab_text",
                            sty.text__uKbFh
                          )}
                        >
                          {"Start now"}
                        </div>
                      }
                      size={"large"}
                    />

                    <PlasmicLink__
                      className={classNames(
                        "all",
                        "a",
                        "a__uRya4",
                        "__wab_text",
                        sty.link__fPqEo
                      )}
                      component={Link}
                      href={"#"}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {"Learn more\u2026"}
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames("all", sty.column__lkAkq)}>
                <SignUpPrompt
                  data-plasmic-name={"signUpPrompt"}
                  data-plasmic-override={overrides.signUpPrompt}
                  className={classNames("__wab_instance", sty.signUpPrompt)}
                />
              </div>
            </div>
          </div>
          <Section
            data-plasmic-name={"valuePropsSection"}
            data-plasmic-override={overrides.valuePropsSection}
            className={classNames("__wab_instance", sty.valuePropsSection)}
          >
            <div className={classNames("all", sty.freeBox__qUdKd)}>
              <div className={classNames("all", sty.freeBox__fmhZf)}>
                <h2
                  className={classNames(
                    "all",
                    "h2",
                    "h2__uRya4",
                    "__wab_text",
                    sty.h2__ojzy9
                  )}
                >
                  {"Proposing values"}
                </h2>
              </div>
              <div className={classNames("all", "__wab_text", sty.text__cjIoo)}>
                {
                  "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                }
              </div>
            </div>
            <div className={classNames("all", sty.freeBox__yDs0J)}>
              <div className={classNames("all", sty.freeBox__wiXdY)}>
                <ValueProp
                  className={classNames("__wab_instance", sty.valueProp__aHcNe)}
                  description={
                    "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                  }
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg__yr7Xv)}
                      role={"img"}
                    />
                  }
                  title={"Powerful"}
                />

                <ValueProp
                  className={classNames("__wab_instance", sty.valueProp__pfIwK)}
                  description={
                    "Consequat scelerisque a eros taciti nisl a sodales."
                  }
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg__ptusA)}
                      role={"img"}
                    />
                  }
                  title={"Faster"}
                />

                <ValueProp
                  className={classNames("__wab_instance", sty.valueProp__djDH)}
                  description={"At ut condimentum amet adipiscing ac diam a."}
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg__z1CYr)}
                      role={"img"}
                    />
                  }
                  title={"Best and brightest"}
                />

                <ValueProp
                  className={classNames("__wab_instance", sty.valueProp__bJvZi)}
                  description={
                    "Donec purus nec vestibulum volutpat vivamus vulputate suspendisse."
                  }
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg___1VfFs)}
                      role={"img"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__eg5L
                      )}
                    >
                      {"Dynamic range"}
                    </div>
                  }
                />
              </div>
              <div className={classNames("all", sty.freeBox__cRj5U)}>
                <ValueProp
                  className={classNames("__wab_instance", sty.valueProp__p4Hns)}
                  description={
                    "Commodo pretium himenaeos nisi potenti ad in ante."
                  }
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg__v0WZ)}
                      role={"img"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__efXU
                      )}
                    >
                      {"Portable"}
                    </div>
                  }
                />

                <ValueProp
                  className={classNames("__wab_instance", sty.valueProp__mpojb)}
                  description={
                    "Magna ullamcorper ut arcu nisi a per facilisis."
                  }
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg___5JLt)}
                      role={"img"}
                    />
                  }
                  title={"Production-ready"}
                />

                <ValueProp
                  className={classNames("__wab_instance", sty.valueProp__namSx)}
                  description={
                    "Ac lobortis praesent sagittis dictumst fermentum vestibulum nunc."
                  }
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg___8JVgj)}
                      role={"img"}
                    />
                  }
                  title={"Magical"}
                />

                <ValueProp
                  className={classNames("__wab_instance", sty.valueProp__jTbIe)}
                  description={
                    "A parturient mi suspendisse nisl inceptos nullam a."
                  }
                  flatIcon={true}
                  icon={
                    <CheckIcon
                      className={classNames("all", sty.svg__zBy3Z)}
                      role={"img"}
                    />
                  }
                  title={"Accessible"}
                />
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"checkpointsSection"}
            data-plasmic-override={overrides.checkpointsSection}
            background={"dark"}
            className={classNames("__wab_instance", sty.checkpointsSection)}
          >
            <div
              className={classNames("all", sty.columns__bbW5P)}
              id={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "features"
                  : "features"
              }
            >
              <div className={classNames("all", sty.column__pH9Iy)}>
                <div className={classNames("all", sty.freeBox__yf8Oh)}>
                  <div
                    className={classNames("all", "__wab_text", sty.text__vgw4K)}
                  >
                    {"Freedoms"}
                  </div>
                  <h2
                    className={classNames(
                      "all",
                      "h2",
                      "h2__uRya4",
                      "__wab_text",
                      sty.h2__pbDnX
                    )}
                  >
                    {"Open by design"}
                  </h2>
                  <div
                    className={classNames("all", "__wab_text", sty.text__w0Phx)}
                  >
                    {
                      "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                    }
                  </div>
                  <div className={classNames("all", sty.freeBox__ckgK)}>
                    <PlasmicLink__
                      className={classNames(
                        "all",
                        "a",
                        "a__uRya4",
                        "__wab_text",
                        sty.link__hpn9W
                      )}
                      component={Link}
                      href={"https://www.plasmic.app/"}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {"Learn more"}
                    </PlasmicLink__>
                    <ChevronRightIcon
                      className={classNames("all", sty.svg__mw2DI)}
                      role={"img"}
                    />
                  </div>
                </div>
              </div>
              <div className={classNames("all", sty.column__xNuGi)}>
                <div className={classNames("all", sty.freeBox__boDQk)}>
                  <ListItem
                    bottomBorder={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "dark"
                        : "dark"
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__eOtUf
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg__d9Zq)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__tV3Md
                      )}
                    >
                      {"Built on capability"}
                    </div>
                  </ListItem>
                  <ListItem
                    bottomBorder={"dark"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__orAck
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg___0Imkd)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__ntrf0
                      )}
                    >
                      {"Highly energetic"}
                    </div>
                  </ListItem>
                  <ListItem
                    bottomBorder={"dark"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__zDp8Q
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg__zaYpH)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__cyyys
                      )}
                    >
                      {"100% transparency and accountability"}
                    </div>
                  </ListItem>
                  <ListItem
                    bottomBorder={"dark"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__okTc7
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg__kNcJn)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text___24ENd
                      )}
                    >
                      {"Refreshing clarity"}
                    </div>
                  </ListItem>
                  <ListItem
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__rG37T
                    )}
                    icon={
                      <CheckCircleIcon
                        className={classNames("all", sty.svg__bGl4K)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__nsg97
                      )}
                    >
                      {"Modern results"}
                    </div>
                  </ListItem>
                </div>
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"pricingSection"}
            data-plasmic-override={overrides.pricingSection}
            background={"dark"}
            className={classNames("__wab_instance", sty.pricingSection)}
          >
            <div className={classNames("all", sty.freeBox__vRQx)}>
              <div className={classNames("all", sty.freeBox__zFzgc)}>
                <div className={classNames("all", sty.freeBox__rOzdo)}>
                  <div
                    className={classNames("all", "__wab_text", sty.text__bYYdD)}
                  >
                    {"Pricing plans"}
                  </div>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__s04Y)}
                >
                  {
                    "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                  }
                </div>
              </div>
              <div className={classNames("all", sty.columns__vtMxO)}>
                <div className={classNames("all", sty.column__cZbF)}>
                  <PriceCard
                    borders={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? []
                        : ["flatRight"]
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__m6Rgd
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__dSx8C
                          )}
                          description={
                            "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__pp0FW)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__a6ZAk
                          )}
                          description={"Mus consequat a justo"}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__aQdu)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                  />
                </div>
                <div className={classNames("all", sty.column__fnbL5)}>
                  <PriceCard
                    borders={[]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__rxzH
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___6LVgY
                          )}
                          description={
                            "Ligula primis mollis sem dignissim semper lectus parturient"
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__lcGbB)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp___8Tglo
                          )}
                          description={
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text__kJMc
                              )}
                            >
                              {"A curabitur dignissim pharetra porta suscipit"}
                            </div>
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__u5Lmp)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__wgM
                          )}
                          description={
                            "Condimentum diam a et sapien praesent potenti torquent a eros"
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__vy3Ie)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__gqs2E
                          )}
                          description={
                            <div
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text___4UgR
                              )}
                            >
                              {"Conubia in hac eu elementum sodales"}
                            </div>
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__r7Bme)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"16"}
                    label={"PRO"}
                    primary={true}
                  />
                </div>
                <div className={classNames("all", sty.column__aYh0Z)}>
                  <PriceCard
                    borders={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? []
                        : ["flatLeft"]
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__ft7Ja
                    )}
                    description={
                      <React.Fragment>
                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__kf634
                          )}
                          description={"Ad nam curae a potenti platea"}
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__jr7Qo)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />

                        <ValueProp
                          className={classNames(
                            "__wab_instance",
                            sty.valueProp__l7Imv
                          )}
                          description={
                            "A adipiscing scelerisque pretium consectetur sem"
                          }
                          flatIcon={true}
                          icon={
                            <CheckIcon
                              className={classNames("all", sty.svg__uoMpp)}
                              role={"img"}
                            />
                          }
                          noTitle={true}
                        />
                      </React.Fragment>
                    }
                    dollars={"10"}
                    label={"Team"}
                  />
                </div>
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"shopBannersSection"}
            data-plasmic-override={overrides.shopBannersSection}
            className={classNames("__wab_instance", sty.shopBannersSection)}
            size={"fullContentWidth"}
          >
            <div className={classNames("all", sty.freeBox__gwYvY)}>
              <Banner
                className={classNames("__wab_instance", sty.banner__chhm)}
                image={{
                  src: "/plasmic/landing_page_starter/images/sunglassesMale.jpg",
                  fullWidth: 2851,
                  fullHeight: 1900,
                  aspectRatio: undefined
                }}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__tusbn
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__yn1Zv
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>
                    <div className={classNames("all", sty.freeBox___3Pggw)}>
                      <PlasmicLink__
                        className={classNames(
                          "all",
                          "a",
                          "a__uRya4",
                          "__wab_text",
                          sty.link__tRrlb
                        )}
                        component={Link}
                        href={"#"}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Go to collection"}
                      </PlasmicLink__>
                      <ChevronRightIcon
                        className={classNames("all", sty.svg__cRikk)}
                        role={"img"}
                      />
                    </div>
                  </React.Fragment>
                }
              />

              <div className={classNames("all", sty.freeBox___7NNMz)}>
                <Banner
                  className={classNames("__wab_instance", sty.banner___2Kl1B)}
                  image={{
                    src: "/plasmic/landing_page_starter/images/sneakers.jpg",
                    fullWidth: 2850,
                    fullHeight: 1900,
                    aspectRatio: undefined
                  }}
                  left={
                    <React.Fragment>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__q5DBb
                        )}
                      >
                        {"Sneakers\nCollection"}
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__zWdfc
                        )}
                      >
                        {"Get 25% off on selected items"}
                      </div>
                      <div className={classNames("all", sty.freeBox__yhKi1)}>
                        <PlasmicLink__
                          className={classNames(
                            "all",
                            "a",
                            "a__uRya4",
                            "__wab_text",
                            sty.link__aLo1J
                          )}
                          component={Link}
                          href={"#"}
                          legacyBehavior={false}
                          platform={"nextjs"}
                        >
                          {"Go to collection"}
                        </PlasmicLink__>
                        <ChevronRightIcon
                          className={classNames("all", sty.svg__lbOr4)}
                          role={"img"}
                        />
                      </div>
                    </React.Fragment>
                  }
                />

                <Banner
                  className={classNames("__wab_instance", sty.banner__c7WfV)}
                  image={{
                    src: "/plasmic/landing_page_starter/images/shirtWoman.png",
                    fullWidth: 1834,
                    fullHeight: 2751,
                    aspectRatio: undefined
                  }}
                  left={
                    <React.Fragment>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__keN5C
                        )}
                      >
                        {"Shirts\nCollection"}
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__uvlMg
                        )}
                      >
                        {"Get 25% off on selected items"}
                      </div>
                      <div className={classNames("all", sty.freeBox__v8DWn)}>
                        <PlasmicLink__
                          className={classNames(
                            "all",
                            "a",
                            "a__uRya4",
                            "__wab_text",
                            sty.link__k8Xd
                          )}
                          component={Link}
                          href={"#"}
                          legacyBehavior={false}
                          platform={"nextjs"}
                        >
                          {"Go to collection"}
                        </PlasmicLink__>
                        <ChevronRightIcon
                          className={classNames("all", sty.svg__wcXxE)}
                          role={"img"}
                        />
                      </div>
                    </React.Fragment>
                  }
                />
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"logoCloudSection"}
            data-plasmic-override={overrides.logoCloudSection}
            className={classNames("__wab_instance", sty.logoCloudSection)}
          >
            <div className={classNames("all", sty.freeBox__ugmu)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___45Rhe)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/loom.svg",
                  fullWidth: 300,
                  fullHeight: 91,
                  aspectRatio: 3.303226
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__kKgWf)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/strapi.svg",
                  fullWidth: 300,
                  fullHeight: 78,
                  aspectRatio: 3.849624
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__qYJoG)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/segment.svg",
                  fullWidth: 300,
                  fullHeight: 62,
                  aspectRatio: 4.87619
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___0JgI0)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/xstate.svg",
                  fullWidth: 300,
                  fullHeight: 94,
                  aspectRatio: 3.2
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__a7X6E)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={{
                  src: "/plasmic/landing_page_starter/images/mapbox.svg",
                  fullWidth: 300,
                  fullHeight: 67,
                  aspectRatio: 4.491228
                }}
              />
            </div>
          </Section>
          <Section
            data-plasmic-name={"testimonialsSection"}
            data-plasmic-override={overrides.testimonialsSection}
            background={"gray"}
            className={classNames("__wab_instance", sty.testimonialsSection)}
          >
            <div className={classNames("all", sty.columns__gy1Px)}>
              <div className={classNames("all", sty.column__q8GOw)}>
                <Testimonial
                  className={classNames(
                    "__wab_instance",
                    sty.testimonial__hwlro
                  )}
                  image={{
                    src: "/plasmic/landing_page_starter/images/tracy.png",
                    fullWidth: 500,
                    fullHeight: 500,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames("all", sty.column__kVOz3)}>
                <Testimonial
                  className={classNames(
                    "__wab_instance",
                    sty.testimonial__jqujf
                  )}
                  image={{
                    src: "/plasmic/landing_page_starter/images/elaine.png",
                    fullWidth: 460,
                    fullHeight: 280,
                    aspectRatio: undefined
                  }}
                  name={"Elaine Benes"}
                  quote={
                    <React.Fragment>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__xaoRp
                        )}
                      >
                        {'"Vestibulum lacinia varius habitant dis aenean.'}
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__qrcpb
                        )}
                      >
                        {
                          'A parturient non ultricies a parturient leo a nascetur at consectetur turpis praesent mus ornare nulla posuere vel parturient."'
                        }
                      </div>
                    </React.Fragment>
                  }
                  title={"Editor, Pendant Publishing"}
                />
              </div>
              <div className={classNames("all", sty.column___7M12U)}>
                <Testimonial
                  className={classNames(
                    "__wab_instance",
                    sty.testimonial__kht9W
                  )}
                  image={{
                    src: "/plasmic/landing_page_starter/images/louis.jpg",
                    fullWidth: 2249,
                    fullHeight: 3000,
                    aspectRatio: undefined
                  }}
                  name={"Louis Huang"}
                  quote={
                    '"Purus dis a primis rhoncus blandit velit suspendisse porta at ullamcorper suscipit a scelerisque sed pharetra facilisi vitae."'
                  }
                  title={
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__wjDuc
                      )}
                    >
                      {"Restaurant Owner, Cattleman's Ranch"}
                    </div>
                  }
                />
              </div>
            </div>
          </Section>
          <CallToActionSection
            data-plasmic-name={"callToActionSection"}
            data-plasmic-override={overrides.callToActionSection}
            className={classNames("__wab_instance", sty.callToActionSection)}
            image={{
              src: "/plasmic/landing_page_starter/images/meeting.jpg",
              fullWidth: 2916,
              fullHeight: 1787,
              aspectRatio: undefined
            }}
          />

          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "navbar",
    "htmlVideo",
    "button",
    "signUpPrompt",
    "valuePropsSection",
    "checkpointsSection",
    "pricingSection",
    "shopBannersSection",
    "logoCloudSection",
    "testimonialsSection",
    "callToActionSection",
    "footerSection"
  ],
  headerHeroSection: [
    "headerHeroSection",
    "navbar",
    "htmlVideo",
    "button",
    "signUpPrompt"
  ],
  navbar: ["navbar"],
  htmlVideo: ["htmlVideo"],
  button: ["button"],
  signUpPrompt: ["signUpPrompt"],
  valuePropsSection: ["valuePropsSection"],
  checkpointsSection: ["checkpointsSection"],
  pricingSection: ["pricingSection"],
  shopBannersSection: ["shopBannersSection"],
  logoCloudSection: ["logoCloudSection"],
  testimonialsSection: ["testimonialsSection"],
  callToActionSection: ["callToActionSection"],
  footerSection: ["footerSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerHeroSection: "div";
  navbar: typeof Navbar;
  htmlVideo: typeof Video;
  button: typeof Button;
  signUpPrompt: typeof SignUpPrompt;
  valuePropsSection: typeof Section;
  checkpointsSection: typeof Section;
  pricingSection: typeof Section;
  shopBannersSection: typeof Section;
  logoCloudSection: typeof Section;
  testimonialsSection: typeof Section;
  callToActionSection: typeof CallToActionSection;
  footerSection: typeof FooterSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    navbar: makeNodeComponent("navbar"),
    htmlVideo: makeNodeComponent("htmlVideo"),
    button: makeNodeComponent("button"),
    signUpPrompt: makeNodeComponent("signUpPrompt"),
    valuePropsSection: makeNodeComponent("valuePropsSection"),
    checkpointsSection: makeNodeComponent("checkpointsSection"),
    pricingSection: makeNodeComponent("pricingSection"),
    shopBannersSection: makeNodeComponent("shopBannersSection"),
    logoCloudSection: makeNodeComponent("logoCloudSection"),
    testimonialsSection: makeNodeComponent("testimonialsSection"),
    callToActionSection: makeNodeComponent("callToActionSection"),
    footerSection: makeNodeComponent("footerSection"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
